name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.2.9519653'
    
    - name: Build strongSwan libraries
      run: |
        # 使用GitHub Actions提供的NDK
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        
        # 准备构建环境
        mkdir -p jni
        cp Android.mk jni/
        cp -r src jni/
        cp Android.common.mk.in jni/Android.common.mk
        
        cat > jni/Application.mk << EOF
        APP_ABI := arm64-v8a armeabi-v7a x86 x86_64
        APP_PLATFORM := android-21
        APP_STL := c++_static
        APP_CPPFLAGS += -std=c++11
        APP_ALLOW_MISSING_DEPS := true
        EOF
        
        # 设置构建路径
        export NDK_PROJECT_PATH=$(pwd)
        
        # 执行构建（编译所有架构）
        ndk-build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strongswan-libs
        path: libs/
